server {
    listen       8080;
    server_name  _;

    access_log  /var/log/nginx/host.access.log  main;
    auth_basic           "Receipt Suggest";
    auth_basic_user_file /usr/share/.htpasswd;

    include /etc/nginx/receipt-suggest-common.conf;
    include /etc/nginx/user-state.conf;
}
